/*
 * Phase 9（後台 A 階段）｜擁有者後台頁面（自含 HTML，只有擁有者能開）。
 * 只顯示聚合人數、會員權益、帳號 metadata 與稽核；呼叫 /api/admin/* 同源帶 session cookie。
 * 不顯示任何飲食明細。
 */
export function getAdminHTML() {
  return [
    '<!DOCTYPE html>',
    '<html lang="zh-Hant"><head><meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width,initial-scale=1">',
    '<title>飲食主場秀 · 擁有者後台</title>',
    '<style>',
    'body{font-family:system-ui,-apple-system,"Noto Sans TC",sans-serif;background:#FBF3E7;color:#4a3728;margin:0;padding:20px;}',
    'h1{font-size:20px;}h2{font-size:15px;margin-top:24px;border-bottom:2px dashed #d8b88f;padding-bottom:6px;}',
    '.card{background:#fff;border:1px solid #e5d5bf;border-radius:12px;padding:14px 16px;margin:10px 0;}',
    '.stat{display:inline-block;margin-right:24px;}.stat b{font-size:24px;color:#b5793a;display:block;}',
    'table{width:100%;border-collapse:collapse;font-size:13px;}td,th{text-align:left;padding:6px 8px;border-bottom:1px solid #eee;}',
    'input,button{font-size:14px;padding:8px 10px;border-radius:8px;border:1px solid #d8b88f;}',
    'button{background:#b5793a;color:#fff;border:none;cursor:pointer;}button.sec{background:#eee;color:#4a3728;}',
    '.msg{padding:8px 10px;border-radius:8px;margin:8px 0;font-size:13px;}',
    '.msg.ok{background:#e6f3e6;}.msg.err{background:#f6e0e0;}',
    '.muted{color:#8a7a68;font-size:12px;}',
    '</style></head><body>',
    '<h1>&#127793; 飲食主場秀 · 擁有者後台</h1>',
    '<div id="gate" class="muted">載入中…</div>',
    '<div id="app" style="display:none">',
    '<h2>加入人數</h2><div class="card"><span class="stat">總帳號<b id="totalUsers">—</b></span><span class="stat">Google 帳號<b id="googleUsers">—</b></span><span class="stat">現有會員<b id="memberCount">—</b></span></div>',
    '<h2>開通 / 撤銷會員</h2><div class="card">',
    '<div>方案：<select id="plan">',
    '<option value="svc3000">3,000 服務包（直接開通・不限期）</option>',
    '<option value="svc35000">35,000 服務包（直接開通・不限期）</option>',
    '<option value="svc48000">48,000 服務包（直接開通・不限期）</option>',
    '<option value="sub1200">1,200 App 年訂閱（365 天）</option>',
    '<option value="trial">7 天免費試用</option>',
    '<option value="custom">自訂天數</option>',
    '</select> <span id="daysWrap" style="display:none">天數：<input id="days" type="number" value="14" style="width:70px"></span></div>',
    '<div class="muted" style="margin-top:6px">服務包（3000/35000/48000）直接開通、不設到期；App 年訂閱固定 365 天。要再加購新功能時才需另外調整。</div>',
    '<div style="margin-top:8px">帳號（可多筆，一行一個 user id 或 Google sub）：</div>',
    '<textarea id="whoList" rows="4" style="width:100%;box-sizing:border-box;font-size:13px;padding:8px;border-radius:8px;border:1px solid #d8b88f" placeholder="每行一個；也可用下方清單按「帶入」逐筆加入"></textarea>',
    '<div style="margin-top:8px"><button id="btnGrant">批次開通</button> <button class="sec" id="btnRevoke">批次撤銷</button> <button class="sec" id="btnClear">清空</button></div>',
    '<div id="actionMsg"></div><div id="resultList"></div></div>',
    '<h2>使用者詢問 / 記錄分享</h2><div class="card"><table id="support"><thead><tr><th>時間</th><th>使用者</th><th>期間</th><th>筆數</th><th>問題</th><th></th></tr></thead><tbody></tbody></table><div id="supportDetail" class="muted" style="margin-top:8px">這裡只會顯示使用者<strong>主動按下送出</strong>分享的記錄快照。點「查看」展開。</div></div>',
    '<h2>最近加入的帳號</h2><div class="card"><table id="signups"><thead><tr><th>名稱</th><th>Email</th><th>身分</th><th>加入時間</th><th>操作</th></tr></thead><tbody></tbody></table><div class="muted">只有帳號資料，無任何飲食內容。Email 需對方「本次改版後」再登入一次才會補上。</div></div>',
    '<h2>現有會員</h2><div class="card"><table id="members"><thead><tr><th>名稱</th><th>Email</th><th>方案</th><th>到期</th></tr></thead><tbody></tbody></table></div>',
    '<h2>每月成本粗估（估計值，非帳單）</h2><div class="card"><div id="cost"></div><div class="muted">真實金額請看 Cloudflare Dashboard。R2 目前只放共用圖、通常為 0；開放使用者上傳後會另估。</div></div>',
    '<h2>近 30 天用量（D1，估計值）</h2><div class="card"><table id="usage"><thead><tr><th>端點</th><th>請求</th><th>rows_read</th><th>rows_written</th></tr></thead><tbody></tbody></table><div class="muted">handler 層估計，供趨勢參考。免費額度：每日 500 萬讀 / 10 萬寫。</div></div>',
    '<h2>近期權益稽核</h2><div class="card"><table id="audit"><thead><tr><th>時間</th><th>動作</th><th>對象</th><th>到期</th><th>操作者</th></tr></thead><tbody></tbody></table></div>',
    '</div>',
    '<script>',
    'function esc(s){return String(s==null?"":s).replace(/[&<>"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;","\\"":"&quot;"}[c];});}',
    'function msg(t,ok){document.getElementById("actionMsg").innerHTML="<div class=\\"msg "+(ok?"ok":"err")+"\\">"+esc(t)+"</div>";}',
    'function rows(sel,html){document.querySelector(sel+" tbody").innerHTML=html;}',
    'function load(){',
    '  fetch("/api/admin/overview",{headers:{"Accept":"application/json"}}).then(function(r){return r.json().then(function(j){return{s:r.status,j:j};});}).then(function(res){',
    '    var g=document.getElementById("gate");',
    '    if(res.s===401){g.textContent="請先用擁有者帳號登入。";return;}',
    '    if(res.s===403){g.textContent="此頁僅限擁有者。";return;}',
    '    if(!res.j||!res.j.ok){g.textContent="載入失敗。";return;}',
    '    g.style.display="none";document.getElementById("app").style.display="block";',
    '    var d=res.j.data;',
    '    document.getElementById("totalUsers").textContent=d.totalUsers;',
    '    document.getElementById("googleUsers").textContent=d.googleUsers;',
    '    document.getElementById("memberCount").textContent=d.activeMembers.length;',
    '    var TMAP={service_3000:"3000服務包",service_35000:"35000服務包",service_48000:"48000服務包",app_annual:"App年訂閱",app_trial:"7天試用",app:"App",companion35000:"35000",companion48000:"48000"};',
    '    var tierLabel=function(t){return TMAP[t]||(t||"");};',
    '    rows("#members",d.activeMembers.map(function(m){return "<tr><td>"+esc(m.display_name||m.user_id)+"</td><td>"+esc(m.email||"—")+"</td><td>"+esc(tierLabel(m.tier))+"</td><td>"+esc(m.valid_until||"無期限")+"</td></tr>";}).join("")||"<tr><td colspan=4 class=muted>尚無會員</td></tr>");',
    '    rows("#signups",(d.recentSignups||[]).map(function(u){return "<tr><td>"+esc(u.display_name||"(未命名)")+"</td><td>"+esc(u.email||"—")+"</td><td>"+esc(u.is_guest?"訪客":(u.auth_provider||""))+"</td><td>"+esc(u.created_at||"")+"</td><td><button class=\\"sec pick\\" data-id=\\""+esc(u.id)+"\\">帶入</button></td></tr>";}).join("")||"<tr><td colspan=5 class=muted>尚無帳號</td></tr>");',
    '    if(d.costEstimate){var c=d.costEstimate;var h="<div><b>估計每月約 US$"+esc(c.estMonthlyUSD)+"</b>（費率核對日 "+esc(c.verified)+"，方案 "+esc(c.plan)+"）</div>";h+="<div class=muted>近30天 D1 讀 "+esc(c.rowsRead30d)+" 列 / 寫 "+esc(c.rowsWritten30d)+" 列；D1 文字資料約 "+esc(c.d1StorageMB)+" MB。免費額度：每日讀 "+esc(c.freeDailyReadLimit)+" / 寫 "+esc(c.freeDailyWriteLimit)+" 列。</div>";h+="<table style=\\"margin-top:8px\\"><tbody>"+(c.lines||[]).map(function(l){return "<tr><td>"+esc(l.item)+"</td><td style=\\"text-align:right\\">US$"+esc(l.usd)+"</td></tr>";}).join("")+"</tbody></table>";document.getElementById("cost").innerHTML=h;}',
    '    rows("#usage",(d.usage30d||[]).map(function(u){return "<tr><td>"+esc(u.endpoint)+"</td><td>"+esc(u.requests)+"</td><td>"+esc(u.rows_read)+"</td><td>"+esc(u.rows_written)+"</td></tr>";}).join("")||"<tr><td colspan=4 class=muted>尚無資料</td></tr>");',
    '    rows("#audit",(d.recentAudit||[]).map(function(a){return "<tr><td>"+esc(a.at)+"</td><td>"+esc(a.action)+"</td><td>"+esc(a.user_id)+"</td><td>"+esc(a.valid_until||"")+"</td><td>"+esc(a.actor||"")+"</td></tr>";}).join("")||"<tr><td colspan=5 class=muted>尚無紀錄</td></tr>");',
    '    loadSupport();',
    '  }).catch(function(){document.getElementById("gate").textContent="載入失敗。";});',
    '}',
    'function loadSupport(){fetch("/api/admin/support",{headers:{"Accept":"application/json"}}).then(function(r){return r.json();}).then(function(j){if(!j||!j.ok){return;}rows("#support",(j.items||[]).map(function(s){return "<tr><td>"+esc((s.created_at||"").slice(0,16))+"</td><td>"+esc(s.display_name||s.email||s.user_id)+"</td><td>"+esc((s.range_from||"").slice(0,10))+"~"+esc((s.range_to||"").slice(0,10))+"</td><td>"+esc(s.record_count)+"</td><td>"+esc((s.question||"").slice(0,30))+"</td><td><button class=\\"sec spv\\" data-id=\\""+esc(s.id)+"\\">查看</button></td></tr>";}).join("")||"<tr><td colspan=6 class=muted>尚無分享</td></tr>");}).catch(function(){});}',
    'function renderSupportDetail(d,item){var pay={};try{pay=JSON.parse(item.payload||"{}");}catch(e){pay={};}var h="<div style=\\"background:#fff;border:1px solid #e5d5bf;border-radius:8px;padding:10px\\">";h+="<div><b>使用者：</b>"+esc(item.display_name||item.email||item.user_id)+"</div>";h+="<div><b>期間：</b>"+esc((item.range_from||"").slice(0,10))+" ~ "+esc((item.range_to||"").slice(0,10))+"（"+esc(item.record_count)+" 筆）</div>";if(item.question){h+="<div style=\\"margin-top:6px\\"><b>問題：</b>"+esc(item.question)+"</div>";}if(pay.identity&&pay.identity.key){h+="<div style=\\"margin-top:6px\\"><b>飲食身份：</b>"+esc(pay.identity.key)+"</div>";}var recs=pay.records||[];h+="<table style=\\"margin-top:8px\\"><thead><tr><th>時間</th><th>行為</th><th>渴望</th></tr></thead><tbody>"+recs.map(function(r){var dt=r.ts?new Date(r.ts).toISOString().slice(0,16):"";return "<tr><td>"+esc(dt)+"</td><td>"+esc(r.beh||"")+"</td><td>"+esc(r.crave||"")+"</td></tr>";}).join("")+"</tbody></table></div>";d.innerHTML=h;}',
    'function post(path,body,cb){fetch(path,{method:"POST",headers:{"Content-Type":"application/json","X-Admin":"1"},body:JSON.stringify(body)}).then(function(r){return r.json().then(function(j){cb(r.status,j);},function(){cb(r.status,null);});}).catch(function(){cb(0,null);});}',
    'function getWhoList(){var t=document.getElementById("whoList").value||"";return t.split(/[\\r\\n,]+/).map(function(s){return s.trim();}).filter(function(s){return s.length>0;});}',
    'function renderResults(j){var el=document.getElementById("resultList");if(!j||!j.results){el.innerHTML="";return;}el.innerHTML="<table style=\\"margin-top:8px\\"><tbody>"+j.results.map(function(r){var st=r.ok?("<span style=\\"color:#2e7d32\\">\\u2713 "+(r.validUntil?("\\u5230\\u671f "+esc(r.validUntil)):"\\u4e0d\\u9650\\u671f")+"</span>"):("<span style=\\"color:#b23\\">\\u2717 "+esc(r.error||"")+"</span>");return "<tr><td style=\\"word-break:break-all\\">"+esc(r.who)+"</td><td>"+st+"</td></tr>";}).join("")+"</tbody></table>";}',
    'document.getElementById("plan").addEventListener("change",function(){document.getElementById("daysWrap").style.display=this.value==="custom"?"inline":"none";});',
    'document.addEventListener("click",function(e){if(e.target&&e.target.classList&&e.target.classList.contains("pick")){var ta=document.getElementById("whoList");var id=e.target.getAttribute("data-id");var cur=ta.value.trim();ta.value=cur?(cur+"\\n"+id):id;}});',
    'document.addEventListener("click",function(e){if(e.target&&e.target.classList&&e.target.classList.contains("spv")){var id=e.target.getAttribute("data-id");var d=document.getElementById("supportDetail");d.textContent="載入中…";fetch("/api/admin/support/get?id="+encodeURIComponent(id),{headers:{"Accept":"application/json"}}).then(function(r){return r.json();}).then(function(j){if(!j||!j.ok||!j.item){d.textContent="載入失敗。";return;}renderSupportDetail(d,j.item);}).catch(function(){d.textContent="載入失敗。";});}});',
    'document.getElementById("btnGrant").addEventListener("click",function(){var list=getWhoList();if(list.length===0){msg("請輸入至少一個帳號",false);return;}var plan=document.getElementById("plan").value;var payload={whoList:list,plan:plan};if(plan==="custom"){payload.days=parseInt(document.getElementById("days").value,10)||14;}post("/api/admin/grant",payload,function(s,j){if(s===200&&j&&j.ok){msg("開通完成："+j.okCount+"/"+j.total+" 筆成功",true);}else{msg("開通未全部成功："+((j&&j.error)||("HTTP "+s)),false);}renderResults(j);load();});});',
    'document.getElementById("btnRevoke").addEventListener("click",function(){var list=getWhoList();if(list.length===0){msg("請輸入至少一個帳號",false);return;}if(!window.confirm("確定撤銷這 "+list.length+" 個帳號的會員？")){return;}post("/api/admin/revoke",{whoList:list},function(s,j){if(s===200&&j&&j.ok){msg("撤銷完成："+j.okCount+"/"+j.total+" 筆成功",true);}else{msg("撤銷未全部成功："+((j&&j.error)||("HTTP "+s)),false);}renderResults(j);load();});});',
    'document.getElementById("btnClear").addEventListener("click",function(){document.getElementById("whoList").value="";document.getElementById("resultList").innerHTML="";});',
    'load();',
    '</script></body></html>'
  ].join('\n');
}
