/*
 * Phase 9（後台 A 階段）｜擁有者後台頁面（自含 HTML，只有擁有者能開）。
 * 只顯示聚合人數、會員權益、帳號 metadata 與稽核；呼叫 /api/admin/* 同源帶 session cookie。
 * 不顯示任何飲食明細。
 */
export function getAdminHTML() {
  return [
    '<!DOCTYPE html>',
    '<html lang="zh-Hant"><head><meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width,initial-scale=1">',
    '<title>飲食主場秀 · 擁有者後台</title>',
    '<style>',
    'body{font-family:system-ui,-apple-system,"Noto Sans TC",sans-serif;background:#FBF3E7;color:#4a3728;margin:0;padding:20px;}',
    'h1{font-size:20px;}h2{font-size:15px;margin-top:24px;border-bottom:2px dashed #d8b88f;padding-bottom:6px;}',
    '.card{background:#fff;border:1px solid #e5d5bf;border-radius:12px;padding:14px 16px;margin:10px 0;}',
    '.stat{display:inline-block;margin-right:24px;}.stat b{font-size:24px;color:#b5793a;display:block;}',
    'table{width:100%;border-collapse:collapse;font-size:13px;}td,th{text-align:left;padding:6px 8px;border-bottom:1px solid #eee;}',
    'input,button{font-size:14px;padding:8px 10px;border-radius:8px;border:1px solid #d8b88f;}',
    'button{background:#b5793a;color:#fff;border:none;cursor:pointer;}button.sec{background:#eee;color:#4a3728;}',
    '.msg{padding:8px 10px;border-radius:8px;margin:8px 0;font-size:13px;}',
    '.msg.ok{background:#e6f3e6;}.msg.err{background:#f6e0e0;}',
    '.muted{color:#8a7a68;font-size:12px;}',
    '</style></head><body>',
    '<h1>&#127793; 飲食主場秀 · 擁有者後台</h1>',
    '<div id="gate" class="muted">載入中…</div>',
    '<div id="app" style="display:none">',
    '<h2>加入人數</h2><div class="card"><span class="stat">總帳號<b id="totalUsers">—</b></span><span class="stat">Google 帳號<b id="googleUsers">—</b></span><span class="stat">現有會員<b id="memberCount">—</b></span></div>',
    '<h2>開通 / 撤銷會員（beta）</h2><div class="card">',
    '<div>使用者 id 或 Google sub：<input id="who" placeholder="可從下方清單按「帶入」" size="44"></div>',
    '<div style="margin-top:8px">天數：<input id="days" type="number" value="14" style="width:70px"> ',
    '<button id="btnGrant">開通</button> <button class="sec" id="btnRevoke">撤銷</button></div>',
    '<div id="actionMsg"></div></div>',
    '<h2>最近加入的帳號</h2><div class="card"><table id="signups"><thead><tr><th>名稱</th><th>身分</th><th>加入時間</th><th>操作</th></tr></thead><tbody></tbody></table><div class="muted">只有帳號資料，無任何飲食內容。</div></div>',
    '<h2>現有會員</h2><div class="card"><table id="members"><thead><tr><th>名稱</th><th>到期</th><th>來源</th></tr></thead><tbody></tbody></table></div>',
    '<h2>近 30 天用量（D1，估計值）</h2><div class="card"><table id="usage"><thead><tr><th>端點</th><th>請求</th><th>rows_read</th><th>rows_written</th></tr></thead><tbody></tbody></table><div class="muted">handler 層估計，供趨勢參考。免費額度：每日 500 萬讀 / 10 萬寫。</div></div>',
    '<h2>近期權益稽核</h2><div class="card"><table id="audit"><thead><tr><th>時間</th><th>動作</th><th>對象</th><th>到期</th><th>操作者</th></tr></thead><tbody></tbody></table></div>',
    '</div>',
    '<script>',
    'function esc(s){return String(s==null?"":s).replace(/[&<>"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;","\\"":"&quot;"}[c];});}',
    'function msg(t,ok){document.getElementById("actionMsg").innerHTML="<div class=\\"msg "+(ok?"ok":"err")+"\\">"+esc(t)+"</div>";}',
    'function rows(sel,html){document.querySelector(sel+" tbody").innerHTML=html;}',
    'function load(){',
    '  fetch("/api/admin/overview",{headers:{"Accept":"application/json"}}).then(function(r){return r.json().then(function(j){return{s:r.status,j:j};});}).then(function(res){',
    '    var g=document.getElementById("gate");',
    '    if(res.s===401){g.textContent="請先用擁有者帳號登入。";return;}',
    '    if(res.s===403){g.textContent="此頁僅限擁有者。";return;}',
    '    if(!res.j||!res.j.ok){g.textContent="載入失敗。";return;}',
    '    g.style.display="none";document.getElementById("app").style.display="block";',
    '    var d=res.j.data;',
    '    document.getElementById("totalUsers").textContent=d.totalUsers;',
    '    document.getElementById("googleUsers").textContent=d.googleUsers;',
    '    document.getElementById("memberCount").textContent=d.activeMembers.length;',
    '    rows("#members",d.activeMembers.map(function(m){return "<tr><td>"+esc(m.display_name||m.user_id)+"</td><td>"+esc(m.valid_until||"無期限")+"</td><td>"+esc(m.source||"")+"</td></tr>";}).join("")||"<tr><td colspan=3 class=muted>尚無會員</td></tr>");',
    '    rows("#signups",(d.recentSignups||[]).map(function(u){return "<tr><td>"+esc(u.display_name||"(未命名)")+"</td><td>"+esc(u.is_guest?"訪客":(u.auth_provider||""))+"</td><td>"+esc(u.created_at||"")+"</td><td><button class=\\"sec pick\\" data-id=\\""+esc(u.id)+"\\">帶入</button></td></tr>";}).join("")||"<tr><td colspan=4 class=muted>尚無帳號</td></tr>");',
    '    rows("#usage",(d.usage30d||[]).map(function(u){return "<tr><td>"+esc(u.endpoint)+"</td><td>"+esc(u.requests)+"</td><td>"+esc(u.rows_read)+"</td><td>"+esc(u.rows_written)+"</td></tr>";}).join("")||"<tr><td colspan=4 class=muted>尚無資料</td></tr>");',
    '    rows("#audit",(d.recentAudit||[]).map(function(a){return "<tr><td>"+esc(a.at)+"</td><td>"+esc(a.action)+"</td><td>"+esc(a.user_id)+"</td><td>"+esc(a.valid_until||"")+"</td><td>"+esc(a.actor||"")+"</td></tr>";}).join("")||"<tr><td colspan=5 class=muted>尚無紀錄</td></tr>");',
    '  }).catch(function(){document.getElementById("gate").textContent="載入失敗。";});',
    '}',
    'function post(path,body,cb){fetch(path,{method:"POST",headers:{"Content-Type":"application/json","X-Admin":"1"},body:JSON.stringify(body)}).then(function(r){return r.json().then(function(j){cb(r.status,j);},function(){cb(r.status,null);});}).catch(function(){cb(0,null);});}',
    'document.addEventListener("click",function(e){if(e.target&&e.target.classList&&e.target.classList.contains("pick")){document.getElementById("who").value=e.target.getAttribute("data-id");}});',
    'document.getElementById("btnGrant").addEventListener("click",function(){var who=document.getElementById("who").value.trim();var days=parseInt(document.getElementById("days").value,10)||14;if(!who){msg("請輸入或帶入 user id",false);return;}post("/api/admin/grant",{who:who,days:days},function(s,j){if(s===200&&j&&j.ok){msg("已開通，到期："+(j.validUntil||""),true);load();}else{msg("開通失敗："+((j&&j.error)||s),false);}});});',
    'document.getElementById("btnRevoke").addEventListener("click",function(){var who=document.getElementById("who").value.trim();if(!who){msg("請輸入或帶入 user id",false);return;}post("/api/admin/revoke",{who:who},function(s,j){if(s===200&&j&&j.ok){msg("已撤銷",true);load();}else{msg("撤銷失敗："+((j&&j.error)||s),false);}});});',
    'load();',
    '</script></body></html>'
  ].join('\n');
}
